zabbixfrontendphp:
  image: viljaste/zabbix_frontend_php:2.2
  hostname: zabbixfrontendphp
  ports:
    - "80:80"
    - "443:443"
  environment:
    - SERVER_NAME=localhost
    - PROTOCOLS=https,http
    - PHP_INI_TIMEZONE=UTC
